name: emeth_agenda
description: EMETH AGENDA - Tu agenda personal con notas, recordatorios y planificación diaria.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado y almacenamiento
  provider: ^6.0.0
  shared_preferences: ^2.0.15

  # Compartir y archivos
  share_plus: ^7.2.1
  path_provider: ^2.1.5
  pdf: ^3.11.3

  # UI y utilidades
  auto_size_text: ^3.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # (Opcionales: solo si los usas en otras partes de tu app)
  screenshot: ^2.1.0
  image: ^4.1.3
  flutter_sound: ^9.2.13
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/agenda_icon.png
    - assets/agenda.png
    - assets/splash/
    - assets/dots.png
    - assets/grid.png
    - assets/lines.png
    - assets/lupa.png
    - assets/mas.png
    - assets/nota.gif
    - assets/pendientes.gif
    - assets/audio.gif
    - assets/cuaderno.jpg
    - assets/hojap.png
    - assets/fonts/Nunito-Bold.ttf
    - assets/fonts/Nunito-BoldItalic.ttf
    - assets/fonts/Nunito-Regular.ttf
    - assets/fontsabc/bold.png
    - assets/fontsabc/italic.png
    - assets/fontsabc/underline.png
    - assets/fontsabc/strikethrough.png
    - assets/fontsabc/font_size.png
    - assets/fontsabc/align_left.png
    - assets/fontsabc/align_center.png
    - assets/fontsabc/align_right.png
    - assets/fontsabc/align_justify.png
    - assets/fontsabc/list_bulleted.png
    - assets/fontsabc/list_numbered.png
    - assets/fontsabc/indent_decrease.png
    - assets/fontsabc/indent_increase.png
    - assets/fontsabc/brush.png
    - assets/fontsabc/color_picker.png
    - assets/borrador.png
    - assets/crayon.png
    - assets/data/calendar/
    - assets/data/quotes/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

# Configuración del Splash Screen
flutter_native_splash:
  color: "#FEF7F0"
  # Cuando tengas tu logo PNG, descomenta la siguiente línea:
  # image: assets/splash/logo.png

# Configuración del Ícono de la App
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
