name: notes_module
description: Módulo de notas diseñado para integrarse en tu aplicación de Biblia. Incluye pantallas y proveedores para crear, listar y editar notas con fondos personalizables.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  share_plus: ^7.2.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  

flutter:
  assets:
    - assets/abc.png
    - assets/camara.png
    - assets/IA.png
    - assets/agenda_icon.png
    - assets/agenda.png
    - assets/dots.png
    - assets/grid.png
    - assets/lines.png
    - assets/lupa.png
    - assets/mas.png
    - assets/nota.gif
    - assets/pendientes.gif
    - assets/compartir.png
    - assets/fonts/Nunito-Bold.ttf
    - assets/fonts/Nunito-BoldItalic.ttf
    - assets/fonts/Nunito-Regular.ttf
    - assets/fontsabc/bold.png
    - assets/fontsabc/italic.png
    - assets/fontsabc/underline.png
    - assets/fontsabc/strikethrough.png
    - assets/fontsabc/font_size.png
    - assets/fontsabc/align_left.png
    - assets/fontsabc/align_center.png
    - assets/fontsabc/align_right.png
    - assets/fontsabc/align_justify.png
    - assets/fontsabc/list_bulleted.png
    - assets/fontsabc/list_numbered.png
    - assets/fontsabc/indent_decrease.png
    - assets/fontsabc/indent_increase.png
    - assets/fontsabc/brush.png
    - assets/fontsabc/color_picker.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
